### ISSUE TITLE
Add support for downloading clothes binary

### ISSUE THREAD

**Issue by McP4nth3r** [Lhoerion/altv-serverupdater#2]
Can you add to the updateScrtipt the clothes.bin that will requiered since the 4.0 alt:V update? :)

**Comment by Unnvaldr** [comment]
Hi, I forgot about it, but after quick research, it's not possible to add it in an elegant way.
File hash is missing from server's update file in CDN, so adding it now would require downloading it every updater's launch.

Let's see if it gets added this week, otherwise I'll proceed with workaround.

**Comment by Unnvaldr** [comment]
Data files are downloaded by default, so after alt:V team adds it to CDN manifest, it won't require any action from me.
Anyway, that binary arrived someday on `dev` branch, so workaround for other branches is still needed and was just implemented.

PS

I've changed logic a bit, now "workarounded" files **will be downloaded only once**.
