### ISSUE TITLE
Install faild

### ISSUE THREAD

**Issue by QuintenQVD0** [Lhoerion/altv-serverupdater#4]
Now the install indeed installed the data files but it did not download the game binary

ptero install script: https://pastebin.com/VKXqgwgK
install logs: https://pteropaste.com/aflp5q
![afbeelding](https://user-images.githubusercontent.com/67589015/179393813-d48d6408-ae14-469a-a0b2-11dde181bfa3.png)

**Comment by Unnvaldr** [comment]
Issue should be solved by 66ff7e3f2447465abcc2fc3baa5f08677262b285. Thanks for the report.
