### ISSUE TITLE
csharp module is missing

### ISSUE THREAD

**Issue by vanlueckn** [Lhoerion/altv-serverupdater#5]
How can i download the csharp module with this script?

I use the linux version. Only the js module gets downloaded.

**Comment by Unnvaldr** [comment]
In `update.cfg` you've `modules` entry, inside you need to append a new value `csharp-module` or `coreclr-module` (both are accepted) and that's it. I'll document it with incoming refactor for data files.

**Comment by vanlueckn** [comment]
Ok thank you 👍
